### PR TITLE
Fix kinopub cdn

### PR DESCRIPTION
**Pull request by Sserebryan**
It looks like kino.pub changed their cdn service. See related issue
#213

### CODE REVIEW

**Comment by jtraub** [comment]
Quite interesting that cdn-azure.net doesn't work for me but alibaba-cdn.net does.

**Comment by Nitrino** [comment]
Hi guys. 
Thank you for your contribution.
I don't have much time right now, but I'm following your discussions and will review the PR soon

**Comment by jtraub** [comment]
@Sserebryan huh, the solution is clever. It works for me now

Thanks a lot

**Comment by Nitrino** [comment]
@Sserebryan Thanks 🔥

**Pull request merged**
